// A19P2F3 — Admin draft templates only; no Meta changes or sending.
let tplRowsA19P2=[],tplEditingA19P2=null,tplBusyA19P2=false,tplViewA19P2=false;
const tplEl=id=>document.getElementById(id);
function tplNoticeA19P2(text,error=false,inside=false){const e=tplEl(inside?'tplEditorNotice':'tplNotice');if(e){e.textContent=text;e.style.color=error?'#ef6b72':'#45c68c';}}
function tplLoadingA19P2(text){tplEl('tplList').innerHTML='<span class="tpl-spinner" aria-hidden="true"></span>'+esc(text);}
async function tplLoadA19P2(){if(state.session?.role!=='Admin'){tplEl('tplList').textContent='ניהול תבניות זמין למנהל בלבד';return;}tplLoadingA19P2('טוען תבניות…');try{const r=await API.request('listMessageTemplatesA19P2');tplRowsA19P2=r.templates||[];tplRenderA19P2();}catch(e){tplEl('tplList').textContent='לא ניתן לטעון תבניות';tplNoticeA19P2(e.message,true);}}
function tplRenderA19P2(){tplEl('tplList').innerHTML=tplRowsA19P2.length?tplRowsA19P2.map(x=>`<div class="tpl-row" data-tpl-row="${esc(x.id)}" title="לחיצה כפולה לתצוגה"><span><strong>${esc(x.name)}</strong> · ${esc(x.eventType||'כל סוגי האירועים')} · ${esc(x.purpose||'')}</span><span class="tpl-row-actions"><button type="button" class="guest-icon-action-v179 edit" data-tpl-edit="${esc(x.id)}" title="עריכה" aria-label="עריכת ${esc(x.name)}">✎</button><button type="button" class="guest-icon-action-v179 delete" data-tpl-delete="${esc(x.id)}" title="מחיקה" aria-label="מחיקת ${esc(x.name)}">🗑</button></span></div>`).join(''):'אין עדיין תבניות. לחץ על ״תבנית חדשה״.';}
function tplEventTypeOptionsA19P2(selected=''){const select=tplEl('tplEventType'),types=Array.isArray(state.eventTypes)?state.eventTypes:[],value=String(selected||'');const rows=types.filter(t=>isTrue(t.active,true)||String(t.name||'')===value||String(t.eventTypeId||t.id||'')===value);select.innerHTML='<option value="">כל סוגי האירועים</option>'+rows.map(t=>`<option value="${esc(String(t.name||''))}">${esc(String(t.name||''))}</option>`).join('');if(value&&!rows.some(t=>String(t.name||'')===value))select.insertAdjacentHTML('beforeend',`<option value="${esc(value)}">${esc(value)} (ערך שמור)</option>`);select.value=value;}
function tplEditA19P2(id,view=false){tplEditingA19P2=tplRowsA19P2.find(x=>String(x.id)===String(id))||null;tplViewA19P2=view;const t=tplEditingA19P2||{};for(const [field,key] of [['tplName','name'],['tplBody','body'],['tplMetaName','metaName'],['tplMetaCategory','metaCategory'],['tplPurpose','purpose']])tplEl(field).value=t[key]||(field==='tplPurpose'?'invitation':'');tplEventTypeOptionsA19P2(t.eventType||'');tplEl('tplEditorTitle').textContent=view?'תצוגת תבנית':t.id?'עריכת תבנית':'תבנית חדשה';tplNoticeA19P2('',false,true);tplEl('tplShade').hidden=false;tplEl('tplImageArea').hidden=!t.id;tplEl('tplImageInfo').textContent=t.imageFileId?'טוען תמונה…':'אין תמונה שמורה';tplShowImageA19P2(t);tplEl('tplSave').hidden=view;tplEl('tplCancel').textContent=view?'סגור':'ביטול';tplEl('tplRemoveImage').hidden=view;tplEl('tplReplaceImage').hidden=view;tplEl('tplImage').disabled=view;for(const id of ['tplName','tplBody','tplEventType','tplMetaName','tplMetaCategory','tplPurpose','tplVariable'])tplEl(id).disabled=view;tplPreviewA19P2();}
function tplCloseA19P2(){++tplImageSeqA19P2;tplSetImageA19P2('');tplEl('tplShade').hidden=true;tplEditingA19P2=null;}
function tplPreviewA19P2(){const values={'שם_המוזמן':'ישראל ישראלי','שם_האירוע':'האירוע לדוגמה','תאריך_האירוע':'01/01/2027','שעת_האירוע':'19:00','מקום_האירוע':'אולם לדוגמה','קישור_RSVP':'https://example.com/rsvp'};tplEl('tplPreviewText').textContent=tplEl('tplBody').value.replace(/\{\{([^{}]+)\}\}/g,(m,k)=>values[k]||m);}
async function tplSaveA19P2(){if(tplBusyA19P2||tplViewA19P2)return;const name=tplEl('tplName').value.trim(),body=tplEl('tplBody').value.trim();if(!name||!body){tplNoticeA19P2('שם תבנית ונוסח הודעה הם שדות חובה',true,true);return;}if(tplRowsA19P2.some(x=>String(x.id)!==String(tplEditingA19P2?.id||'')&&String(x.name||'').trim().toLocaleLowerCase()===name.toLocaleLowerCase())){tplNoticeA19P2('כבר קיימת תבנית בשם זה',true,true);return;}tplBusyA19P2=true;const b=tplEl('tplSave');b.disabled=true;b.innerHTML='<span class="tpl-spinner" aria-hidden="true"></span>שומר…';tplNoticeA19P2('שומר…',false,true);try{const t={id:tplEditingA19P2?.id||'',name,body,eventType:tplEl('tplEventType').value,purpose:tplEl('tplPurpose').value,metaName:tplEl('tplMetaName').value,metaCategory:tplEl('tplMetaCategory').value};await API.request('saveMessageTemplateA19P2',{template:t});tplNoticeA19P2('התבנית נשמרה בהצלחה',false,true);await tplLoadA19P2();tplCloseA19P2();tplNoticeA19P2('התבנית נשמרה בהצלחה');}catch(e){tplNoticeA19P2(e.message,true,true);}finally{tplBusyA19P2=false;b.disabled=false;b.textContent='שמור טיוטה';}}
async function tplDeleteA19P2(id){const row=tplRowsA19P2.find(x=>String(x.id)===String(id));if(!row||tplBusyA19P2)return;const shade=document.createElement('div');shade.className='tpl-shade';shade.innerHTML='<div class="panel tpl-dialog" role="alertdialog" aria-modal="true"><h2>מחיקת תבנית</h2><p></p><div role="status" data-status></div><div class="actions"><button type="button" class="secondary" data-cancel>ביטול</button><button type="button" class="danger" data-confirm>כן, מחק</button></div></div>';shade.querySelector('p').textContent='למחוק את התבנית ״'+row.name+'״? המחיקה אינה מוחקת תבנית ב־Meta.';tplEl('page-messages').appendChild(shade);shade.querySelector('[data-cancel]').onclick=()=>shade.remove();shade.querySelector('[data-confirm]').onclick=async()=>{if(tplBusyA19P2)return;tplBusyA19P2=true;const btn=shade.querySelector('[data-confirm]');btn.disabled=true;btn.innerHTML='<span class="tpl-spinner"></span>מוחק…';try{await API.request('deleteMessageTemplateA19P2',{id});shade.remove();await tplLoadA19P2();tplNoticeA19P2('התבנית נמחקה בהצלחה');}catch(e){shade.querySelector('[data-status]').textContent=e.message;shade.querySelector('[data-status]').style.color='#ef6b72';btn.disabled=false;btn.textContent='נסה שוב';}finally{tplBusyA19P2=false;}};}
async function tplImageA19P2(file){if(!file||!tplEditingA19P2?.id||tplViewA19P2)return;if(file.size>4*1024*1024){tplNoticeA19P2('תמונה גדולה מ־4MB',true,true);return;}tplNoticeA19P2('מעלה תמונה…',false,true);const localUrl=URL.createObjectURL(file);tplSetImageA19P2(localUrl);try{const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});const oldId=tplEditingA19P2.imageFileId;const r=await API.request('uploadMessageTemplateImageA19P2',{id:tplEditingA19P2.id,fileName:file.name,mime:file.type,base64});if(oldId)tplImageCacheA19P2.delete(String(oldId));if(r.template.imageFileId)tplImageCacheA19P2.set(String(r.template.imageFileId),'data:'+file.type+';base64,'+base64);await tplLoadA19P2();tplEditA19P2(r.template.id);tplNoticeA19P2('התמונה נשמרה ב־Drive',false,true);}catch(e){tplNoticeA19P2(e.message,true,true);}finally{URL.revokeObjectURL(localUrl);}}

let tplImageSeqA19P2=0;
const tplImageCacheA19P2=new Map();
function tplSetImageA19P2(src){for(const id of ['tplImagePreview','tplImageView']){const el=tplEl(id);if(!el)continue;el.hidden=!src;if(src)el.src=src;else el.removeAttribute('src');}}
async function tplShowImageA19P2(template){const seq=++tplImageSeqA19P2;tplSetImageA19P2('');if(!template?.imageFileId)return;const cached=tplImageCacheA19P2.get(String(template.imageFileId));if(cached){tplSetImageA19P2(cached);tplEl('tplImageInfo').textContent='תמונה שמורה';return;}try{const result=await API.request('getMessageTemplateImageA19P2',{id:template.id});if(seq!==tplImageSeqA19P2||String(tplEditingA19P2?.id)!==String(template.id))return;if(!/^image\/(png|jpeg|webp)$/.test(result.mime||'')||!/^[A-Za-z0-9+/=]+$/.test(result.base64||''))throw new Error('פורמט תמונה לא תקין');const imageSrc='data:'+result.mime+';base64,'+result.base64;tplImageCacheA19P2.set(String(template.imageFileId),imageSrc);tplSetImageA19P2(imageSrc);tplEl('tplImageInfo').textContent='תמונה שמורה';}catch(e){if(seq===tplImageSeqA19P2){tplEl('tplImageInfo').textContent='לא ניתן לטעון תמונה: '+e.message;tplSetImageA19P2('');}}}
tplEl('tplNew').addEventListener('click',()=>tplEditA19P2(''));
tplEl('tplList').addEventListener('click',e=>{const edit=e.target.closest('[data-tpl-edit]'),del=e.target.closest('[data-tpl-delete]');if(edit)tplEditA19P2(edit.dataset.tplEdit);else if(del)tplDeleteA19P2(del.dataset.tplDelete);});
tplEl('tplList').addEventListener('dblclick',e=>{if(e.target.closest('button'))return;const row=e.target.closest('[data-tpl-row]');if(row)tplEditA19P2(row.dataset.tplRow,true);});
tplEl('tplVariable').addEventListener('change',e=>{const v=e.target.value,t=tplEl('tplBody');if(!v)return;const i=t.selectionStart;t.value=t.value.slice(0,i)+v+t.value.slice(t.selectionEnd);t.focus();t.setSelectionRange(i+v.length,i+v.length);e.target.value='';tplPreviewA19P2();});
tplEl('tplBody').addEventListener('input',tplPreviewA19P2);tplEl('tplSave').addEventListener('click',tplSaveA19P2);tplEl('tplCancel').addEventListener('click',tplCloseA19P2);tplEl('tplImage').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';tplImageA19P2(file);});tplEl('tplReplaceImage').addEventListener('click',()=>tplEl('tplImage').click());
tplEl('tplRemoveImage').addEventListener('click',async()=>{if(!tplEditingA19P2?.id||!confirm('להסיר את התמונה מהתבנית?'))return;try{const oldId=tplEditingA19P2.imageFileId;const r=await API.request('removeMessageTemplateImageA19P2',{id:tplEditingA19P2.id});if(oldId)tplImageCacheA19P2.delete(String(oldId));await tplLoadA19P2();tplEditA19P2(r.template.id);tplNoticeA19P2('התמונה הוסרה מהתבנית',false,true);}catch(e){tplNoticeA19P2(e.message,true,true);}});
