/* V1.1.90A19P2F14Z58D5C */
// A19P2F3 — Admin draft templates only; no Meta changes or sending.
let tplRowsA19P2=[],tplEditingA19P2=null,tplBusyA19P2=false,tplViewA19P2=false;
// F14Z18 — V3 BODY is read from Meta; there is no hard-coded local copy.
const TPL_V3_META_NAME_F14F='family_event_invitation_v3';
function tplAlignV3BodyF14F_(){return false;}
async function tplSyncAllFromMetaF14Z32_(){const environment=tplEl('tplSyncEnvironment')?.value||'PRODUCTION';return API.request('syncAllMetaTemplatesF14Z50',{environment});}

const tplEl=id=>document.getElementById(id);
// F14Z52 — invalidate the WhatsApp send/template preview caches after template settings or image changes.
// This replaces the missing legacy helper that caused template image save/remove to fail in the UI.
function tplInvalidateWaSendCacheF14G_(){
  if(typeof state!=='object'||!state)return;
  if(state.waSendTemplatesCacheF14G instanceof Map)state.waSendTemplatesCacheF14G.clear();
  else state.waSendTemplatesCacheF14G=new Map();
  if(state.waSendTemplateImagesF14G instanceof Map)state.waSendTemplateImagesF14G.clear();
  else state.waSendTemplateImagesF14G=new Map();
}
function tplNoticeA19P2(text,error=false,inside=false){const e=tplEl(inside?'tplEditorNotice':'tplNotice');if(e){e.textContent=text;e.style.color=error?'#ef6b72':'#45c68c';}}
function tplLoadingA19P2(text){tplEl('tplList').innerHTML='<span class="tpl-spinner" aria-hidden="true"></span>'+esc(text);}
async function tplLoadA19P2(){const role=state.session?.role||'';if(!['Admin','EventManager'].includes(role)){tplEl('tplList').textContent='אין הרשאה לצפייה בתבניות';return;}const admin=role==='Admin';tplEl('tplSyncMeta').hidden=!admin;tplEl('tplAdminNote').hidden=!admin;tplEl('tplManagerNote').hidden=admin;tplEl('tplPageTitle').textContent=admin?'ניהול תבניות WhatsApp':'תבניות WhatsApp';tplLoadingA19P2('טוען תבניות…');try{const r=await API.request('listMessageTemplatesA19P2');const env=String(tplEl('tplSyncEnvironment')?.value||'PRODUCTION').toUpperCase();tplRowsA19P2=(r.templates||[]).filter(x=>(admin||String(x.active).toLowerCase()==='true')&&String(x.environment||'PRODUCTION').toUpperCase()===env);tplRenderA19P2();}catch(e){tplEl('tplList').textContent='לא ניתן לטעון תבניות';tplNoticeA19P2(e.message,true);}}
function tplPurposeLabelF14Z32_(p){return ({invitation:'הזמנה לאירוע',rsvp_update:'תזכורת לאישור הגעה',table_update:'שיוך שולחנות וניווט',table_payment_update:'שיוך שולחנות, ניווט ותשלום',thank_you:'תודה למשתתפים'})[String(p||'')]||String(p||'');}
function tplRenderA19P2(){const admin=state.session?.role==='Admin';tplEl('tplList').innerHTML=tplRowsA19P2.length?tplRowsA19P2.map(x=>{const invitation=String(x.purpose||'')==='invitation';const edit=admin||invitation?`<button type="button" class="guest-icon-action-v179 edit" data-tpl-edit="${esc(x.id)}" title="${admin?'עריכת הגדרות':'החלפת תמונת הזמנה'}" aria-label="${admin?'עריכת':'תמונת'} ${esc(x.name)}">✎</button>`:'';const send='';return `<div class="tpl-row" data-tpl-row="${esc(x.id)}" title="לחיצה כפולה לתצוגה"><span><strong>${esc(x.name)}</strong>${admin?' · '+esc(String(x.environment||'PRODUCTION'))+' · '+(String(x.active).toLowerCase()==='true'?'פעילה':'לא פעילה'):''}</span><span class="tpl-row-actions">${send}${edit}</span></div>`}).join(''):'אין תבניות זמינות.';}
function tplEventTypeOptionsA19P2(selected=''){const select=tplEl('tplEventType'),types=Array.isArray(state.eventTypes)?state.eventTypes:[],value=String(selected||'');const rows=types.filter(t=>isTrue(t.active,true)||String(t.name||'')===value||String(t.eventTypeId||t.id||'')===value);select.innerHTML='<option value="">כל סוגי האירועים</option>'+rows.map(t=>`<option value="${esc(String(t.name||''))}">${esc(String(t.name||''))}</option>`).join('');if(value&&!rows.some(t=>String(t.name||'')===value))select.insertAdjacentHTML('beforeend',`<option value="${esc(value)}">${esc(value)} (ערך שמור)</option>`);select.value=value;}
function tplManagerPreviewF14Z32_(t){const ev=typeof activeEvent==='function'?activeEvent():null;const values={'פנייה_אישית':'משפחה יקרה','שם_המוזמן':'ישראל ישראלי','שם_האירוע':String(ev?.name||'האירוע המשפחתי'),'תאריך_האירוע':String(ev?.eventDate||'01/01/2027'),'שעת_האירוע':String(ev?.eventTime||'19:00'),'מקום_האירוע':String(ev?.venue||ev?.location||'מקום האירוע'),'קישור_RSVP':'קישור לאישור הגעה'};let body=String(t?.body||'').replace(/\{\{\s*([^{}]+?)\s*\}\}/g,(m,k)=>values[String(k).trim()]||({'1':'משפחה יקרה','2':values['שם_האירוע'],'3':values['תאריך_האירוע']})[String(k).trim()]||'פרטי האירוע');let box=tplEl('tplManagerPreviewF14Z32');if(!box){box=document.createElement('div');box.id='tplManagerPreviewF14Z32';box.className='tpl-manager-preview-f14z27';tplEl('tplEditorTitle').insertAdjacentElement('afterend',box);}box.innerHTML=`<div class="wa-preview-card-f14g"><div class="wa-preview-image-wrap-f14g"><img id="tplManagerImageF14Z32" alt="תמונת הזמנה" hidden></div><div class="wa-preview-body-f14g">${esc(body)}</div><div class="wa-preview-button-f14g">אישור הגעה</div></div>`;}
function tplEditA19P2(id,view=false){tplEditingA19P2=tplRowsA19P2.find(x=>String(x.id)===String(id))||null;if(!tplEditingA19P2)return;const admin=state.session?.role==='Admin',invitation=String(tplEditingA19P2.purpose||'')==='invitation';if(!admin&&!invitation)view=true;tplViewA19P2=view;const t=tplEditingA19P2;for(const [field,key] of [['tplName','name'],['tplBody','body'],['tplMetaName','metaName'],['tplMetaStatus','metaStatus'],['tplMetaCategory','metaCategory'],['tplPurpose','purpose']])tplEl(field).value=t[key]||'';tplEl('tplActive').value=String(t.active).toLowerCase()==='true'?'true':'false';tplEventTypeOptionsA19P2(t.eventType||'');tplEl('tplEditorTitle').textContent=admin?(view?'תצוגת תבנית':'עריכת הגדרות תבנית'):(invitation?'תמונת הזמנה':'תצוגת תבנית');tplNoticeA19P2('',false,true);tplEl('tplShade').hidden=false;tplEl('tplImageArea').hidden=!t.id;tplEl('tplImageInfo').textContent=t.imageFileId?'טוען תמונה…':'אין תמונה שמורה';tplShowImageA19P2(t);tplEl('tplSave').hidden=!admin||view;tplEl('tplCancel').textContent=view||!admin?'סגור':'ביטול';const canImage=admin||(!view&&invitation);tplEl('tplRemoveImage').hidden=!(admin||(!view&&invitation));tplEl('tplReplaceImage').hidden=!canImage;tplEl('tplImage').disabled=!canImage;for(const fid of ['tplName','tplEventType','tplPurpose','tplActive'])tplEl(fid).disabled=!admin||view;for(const fid of ['tplBody','tplMetaName','tplMetaStatus','tplMetaCategory'])tplEl(fid).disabled=true;tplPreviewA19P2();const manager=!admin;if(manager){tplManagerPreviewF14Z32_(t);const editor=tplEl('tplEditor');editor?.classList.add('tpl-manager-mode-f14z27');}else{tplEl('tplEditor')?.classList.remove('tpl-manager-mode-f14z27');const mp=tplEl('tplManagerPreviewF14Z32');if(mp)mp.remove();}}
function tplCloseA19P2(){++tplImageSeqA19P2;tplSetImageA19P2('');tplEl('tplShade').hidden=true;tplEditingA19P2=null;}
function tplPreviewA19P2(){const values={'פנייה_אישית':'משפחת כהן היקרה','שם_המוזמן':'ישראל ישראלי','שם_האירוע':'האירוע לדוגמה','תאריך_האירוע':'01/01/2027','שעת_האירוע':'19:00','מקום_האירוע':'אולם לדוגמה','קישור_RSVP':'https://example.com/rsvp'};tplEl('tplPreviewText').textContent=tplEl('tplBody').value.replace(/\{\{([^{}]+)\}\}/g,(m,k)=>values[k]||m);}
async function tplSaveA19P2(){if(tplBusyA19P2||tplViewA19P2||!tplEditingA19P2)return;const name=tplEl('tplName').value.trim();if(!name){tplNoticeA19P2('שם תצוגה הוא שדה חובה',true,true);return;}if(tplRowsA19P2.some(x=>String(x.id)!==String(tplEditingA19P2.id)&&String(x.name||'').trim().toLocaleLowerCase()===name.toLocaleLowerCase())){tplNoticeA19P2('כבר קיימת תבנית בשם זה',true,true);return;}tplBusyA19P2=true;const b=tplEl('tplSave');b.disabled=true;b.innerHTML='<span class="tpl-spinner" aria-hidden="true"></span>שומר…';try{const t={id:tplEditingA19P2.id,name,eventType:tplEl('tplEventType').value,purpose:tplEl('tplPurpose').value,active:tplEl('tplActive').value==='true'};await API.request('saveMessageTemplateA19P2',{template:t});tplInvalidateWaSendCacheF14G_();await tplLoadA19P2();tplCloseA19P2();tplNoticeA19P2('הגדרות התבנית נשמרו בהצלחה');}catch(e){tplNoticeA19P2(e.message,true,true);}finally{tplBusyA19P2=false;b.disabled=false;b.textContent='שמור הגדרות';}}
async function tplImageA19P2(file){if(!file||!tplEditingA19P2?.id||tplViewA19P2)return;if(file.size>4*1024*1024){tplNoticeA19P2('תמונה גדולה מ־4MB',true,true);return;}tplNoticeA19P2('מעלה תמונה…',false,true);const localUrl=URL.createObjectURL(file);tplSetImageA19P2(localUrl);try{const base64=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});const oldId=tplEditingA19P2.imageFileId;const r=await API.request('uploadMessageTemplateImageA19P2',{id:tplEditingA19P2.id,fileName:file.name,mime:file.type,base64});if(oldId)tplImageCacheA19P2.delete(String(oldId));tplInvalidateWaSendCacheF14G_();if(r.template.imageFileId)tplImageCacheA19P2.set(String(r.template.imageFileId),'data:'+file.type+';base64,'+base64);await tplLoadA19P2();tplEditA19P2(r.template.id);tplNoticeA19P2('התמונה נשמרה ב־Drive',false,true);}catch(e){tplNoticeA19P2(e.message,true,true);}finally{URL.revokeObjectURL(localUrl);}}

let tplImageSeqA19P2=0;
const tplImageCacheA19P2=new Map();
function tplSetImageA19P2(src){const managerImg=tplEl('tplManagerImageF14Z32');if(managerImg){managerImg.hidden=!src;if(src)managerImg.src=src;else managerImg.removeAttribute('src');}for(const id of ['tplImagePreview','tplImageView']){const el=tplEl(id);if(!el)continue;el.hidden=!src;if(src)el.src=src;else el.removeAttribute('src');}}
async function tplShowImageA19P2(template){const seq=++tplImageSeqA19P2;tplSetImageA19P2('');if(!template?.imageFileId)return;const cached=tplImageCacheA19P2.get(String(template.imageFileId));if(cached){tplSetImageA19P2(cached);tplEl('tplImageInfo').textContent='תמונה שמורה';return;}try{const result=await API.request('getMessageTemplateImageA19P2',{id:template.id});if(seq!==tplImageSeqA19P2||String(tplEditingA19P2?.id)!==String(template.id))return;if(!/^image\/(png|jpeg|webp)$/.test(result.mime||'')||!/^[A-Za-z0-9+/=]+$/.test(result.base64||''))throw new Error('פורמט תמונה לא תקין');const imageSrc='data:'+result.mime+';base64,'+result.base64;tplImageCacheA19P2.set(String(template.imageFileId),imageSrc);tplSetImageA19P2(imageSrc);tplEl('tplImageInfo').textContent='תמונה שמורה';}catch(e){if(seq===tplImageSeqA19P2){tplEl('tplImageInfo').textContent='לא ניתן לטעון תמונה: '+e.message;tplSetImageA19P2('');}}}
tplEl('tplSyncEnvironment')?.addEventListener('change',()=>{tplNoticeA19P2('');tplLoadA19P2();});
tplEl('tplSyncMeta').addEventListener('click',async()=>{if(tplBusyA19P2)return;tplBusyA19P2=true;const b=tplEl('tplSyncMeta');b.disabled=true;b.innerHTML='<span class="tpl-spinner"></span>מסנכרן…';tplNoticeA19P2('מסנכרן תבניות מ־Meta…');try{const r=await tplSyncAllFromMetaF14Z32_();await tplLoadA19P2();tplNoticeA19P2(`${r.environment}: סונכרנו ${r.found}/${r.total} תבניות · ${r.changed} עודכנו`);}catch(e){tplNoticeA19P2('הסנכרון נכשל: '+e.message,true);}finally{tplBusyA19P2=false;b.disabled=false;b.textContent='🔄 סנכרון תבניות מ־Meta';}});
tplEl('tplList').addEventListener('click',e=>{const edit=e.target.closest('[data-tpl-edit]');if(edit)tplEditA19P2(edit.dataset.tplEdit);});
tplEl('tplList').addEventListener('dblclick',e=>{if(e.target.closest('button'))return;const row=e.target.closest('[data-tpl-row]');if(row)tplEditA19P2(row.dataset.tplRow,true);});
tplEl('tplSave').addEventListener('click',tplSaveA19P2);tplEl('tplCancel').addEventListener('click',tplCloseA19P2);tplEl('tplImage').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';tplImageA19P2(file);});tplEl('tplReplaceImage').addEventListener('click',()=>tplEl('tplImage').click());
tplEl('tplRemoveImage').addEventListener('click',async()=>{if(!tplEditingA19P2?.id||!confirm('להסיר את התמונה מהתבנית?'))return;try{const oldId=tplEditingA19P2.imageFileId;const r=await API.request('removeMessageTemplateImageA19P2',{id:tplEditingA19P2.id});tplInvalidateWaSendCacheF14G_();if(oldId)tplImageCacheA19P2.delete(String(oldId));await tplLoadA19P2();tplEditA19P2(r.template.id);tplNoticeA19P2('התמונה הוסרה מהתבנית',false,true);}catch(e){tplNoticeA19P2(e.message,true,true);}});
